spring:
  application:
    name: fleet-api
  messages:
    basename: messages/messages
    encoding: UTF-8
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
  servlet.context-path: /api




