server:
  tomcat:
    accept-count: 256

spring:
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/fleet
    username: postgres
    password: postgres